context:
  version: "5.8.16"

package:
  name: pspg
  version: ${{ version }}

source:
  url: https://github.com/okbob/pspg/archive/${{ version }}.tar.gz
  sha256: 3dcfb810cc6675cac6e3ea53775a6f819e0e12e0d2bde8122e3136b740f38ae5

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - libpq
    - ncurses
    - readline

tests:
  - script:
      - pspg --help

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Unix pager optimized for psql
  homepage: https://github.com/okbob/pspg
  repository: https://github.com/okbob/pspg

extra:
  recipe-maintainers:
    - danielnachun
