context:
  version: "5.8.15"

package:
  name: pspg
  version: ${{ version }}

source:
  url: https://github.com/okbob/pspg/archive/${{ version }}.tar.gz
  sha256: c5aebbc16c35d6386fe9f5d8ab34c31c4a7b859017adb1a856aa2cacaec5cafc

build:
  number: 0
  skip: win

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
    - pkg-config
  host:
    - libpq
    - ncurses
    - readline

tests:
  - script:
      - pspg --help

about:
  license: BSD-2-Clause
  license_file: LICENSE
  summary: Unix pager optimized for psql
  homepage: https://github.com/okbob/pspg
  repository: https://github.com/okbob/pspg

extra:
  recipe-maintainers:
    - danielnachun
